# Site settings
title: Swolejourn
email: sageman@gmail.com
description: >
  My personal training log and testament to Brodin.
baseurl: "/swolejourn"
url: "https://carltonstedman.github.io/"
twitter_username: carltonstedman
github_username: carltonstedman
timezone: America/New_York

# Build settings
markdown: redcarpet
